[package]
name = "tarkov-discord-bot"
version = "0.1.0"
edition = "2021"

[dependencies]
graphql_client = { version = "0.14.0" }
reqwest = { version = "0.12.8", features = ["json"] }
serde = "1.0.210"
strsim = "0.11.1"
tokio = { version = "1.40.0", features = ["full"] }
